# Generated by Django 6.0.6 on 2026-06-16 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('book_image_url', models.URLField(blank=True)),
                ('synopsis', models.TextField(blank=True)),
                ('author', models.CharField(max_length=60)),
                ('rating', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('profile_image_url', models.URLField(blank=True)),
                ('bio_text', models.TextField(blank=True)),
                ('join_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('character_image_url', models.URLField(blank=True)),
                ('rating', models.IntegerField(blank=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookreview.book')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookreview.book')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookreview.character')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookreview.profile')),
            ],
        ),
    ]
