# Generated by Django 6.0.6 on 2026-06-18 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookreview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCommment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookreview.book')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookreview.profile')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookreview.character')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookreview.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
