# Generated by Django 6.0.5 on 2026-06-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookreview', '0002_bookcommment_charactercomment_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcommment',
            name='raiting',
            field=models.IntegerField(blank=True, default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charactercomment',
            name='raiting',
            field=models.IntegerField(blank=True, default=2),
            preserve_default=False,
        ),
    ]
