# Generated by Django 6.0.5 on 2026-06-21 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookreview', '0003_bookcommment_raiting_charactercomment_raiting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookcommment',
            old_name='raiting',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='charactercomment',
            old_name='raiting',
            new_name='rating',
        ),
    ]
