# Generated by Django 6.0.5 on 2026-06-21 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookreview', '0004_rename_raiting_bookcommment_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='numrating',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='numrating',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
