# Generated by Django 6.0.5 on 2026-06-22 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookreview', '0005_book_numrating_character_numrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='bookcommment',
            name='rating',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='rating',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='charactercomment',
            name='rating',
            field=models.FloatField(blank=True),
        ),
    ]
