# Generated by Django 6.0.5 on 2026-06-25 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookreview', '0009_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='character_image_url',
        ),
    ]
