# Generated by Django 6.0.5 on 2026-05-30 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0003_photo_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
